generator-import:
  generated-by: 'MCUXpresso config tools Generated: 10/03/2025 10:59:09'
  for-device: MCXN947
  for-board: FRDM-MCXN947
  groups:
  - group: ConfigTools board
    files:
    - file: board/clock_config.c
    - file: board/clock_config.h
    - file: board/peripherals.c
    - file: board/peripherals.h
    - file: board/pin_mux.c
    - file: board/pin_mux.h
    - file: trustzone/resource_config.c
    - file: trustzone/resource_config.h
